apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config
  namespace: default
data:
  RabbitMq__Host: "rabbitmq-service"
  ASPNETCORE_ENVIRONMENT: "Production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
      - name: payments-api
        image: fcg-payments-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: payments-config
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: default
spec:
  selector:
    app: payments-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP